cSpaceViz_Gradient_Wavefront_planners: factory.object_factory.ObjectFactory Class Reference
factory.object_factory.ObjectFactory Class Reference
Public Member Functions
def __init__ (self)
def register_builder (self, key, builder)
def create (self, key, **kwargs)
Detailed Description
Definition at line 7 of file object_factory.py.
Constructor & Destructor Documentation
__init__()
def factory.object_factory.ObjectFactory.__init__ (self)
Definition at line 12 of file object_factory.py.
References factory.object_factory.ObjectFactory._builders.
Member Function Documentation
create()
def factory.object_factory.ObjectFactory.create (self, key, ** kwargs)
Definition at line 41 of file object_factory.py.
References factory.object_factory.ObjectFactory._builders.
Referenced by spaces.factory.RobotSpaceCollection.get(), planners.factory.PlannerCreator.get(), and robots.factory.RobotWarehouse.get().
register_builder()
def factory.object_factory.ObjectFactory.register_builder (self, key, builder)
Definition at line 26 of file object_factory.py.
References factory.object_factory.ObjectFactory._builders.
The documentation for this class was generated from the following file:
factory/object_factory.py