cSpaceViz_Gradient_Wavefront_planners: main Namespace Reference
main Namespace Reference
Functions
def main ()
def simRunner (shouldSavePlots, basePlotDir, simType)
def runCspaceViz (configFileName, shouldSavePlots, baseSaveFName)
def runGradientPlanner (configFileName, shouldSavePlots, baseSaveFName)
def getConfigPaths (simType)
Function Documentation
getConfigPaths()
def main.getConfigPaths (simType)
Definition at line 108 of file main.py.
Referenced by simRunner().
main()
def main.main ()
Definition at line 10 of file main.py.
References os_calls.clear_screen(), and simRunner().
runCspaceViz()
def main.runCspaceViz (configFileName, shouldSavePlots, baseSaveFName)
Definition at line 52 of file main.py.
Referenced by simRunner().
runGradientPlanner()
def main.runGradientPlanner (configFileName, shouldSavePlots, baseSaveFName)
Definition at line 79 of file main.py.
Referenced by simRunner().
simRunner()
def main.simRunner (shouldSavePlots, basePlotDir, simType)
Definition at line 29 of file main.py.
References getConfigPaths(), runCspaceViz(), and runGradientPlanner().
Referenced by main().