# list of lengths of each link
linkLengths:
  - 10
  - 10
  - 10

# specify how far in from the end of each link the joint is
jointOffset: 1

# specify a list of joint angles to do forward kinematics
# [rad]
desJointAnglesSet:
  - [0.78539816339, 1.57079632679, -0.52359877559]

# specify a list of final end effector positions to do inverse kinematics
desEndEffectorLocations:
  - [0, 4]