# each list element is a list of tuples containing the coordinatesof the
# vertices of the polygonal obstacles in the workspace
WO:
  - [[-6, -6], [25, -6], [25, -5], [-6, -5]]
  - [[-6, 5], [30, 5], [30, 6], [-6, 6]]
  - [[-6, -5], [-5, -5], [-5, 5], [-6, 5]]
  - [[4, -5], [5, -5], [5, 1], [4, 1]]
  - [[9, 0], [10, 0], [10, 5], [9, 5]]
  - [[14, -5], [15, -5], [15, 1], [14, 1]]
  - [[19, 0], [20, 0], [20, 5], [19, 5]]
  - [[24, -5], [25, -5], [25, 1], [24, 1]]
  - [[29, 0], [30, 0], [30, 5], [29, 5]]

# coordinates of the robot start state in state space
# [x, y]
startState: [0, 0]

# coordinates of the robot goal state in the workspace
# [x, y]
goalState: [35, 0]


# determines N such that CSpace is discretized into an NxN grid
# not really used for the PRM planner, so keep it very sparse for speed
linearDiscretizationDensity: 3

# determines whether the CSpace will be made square when enlarged for planning.
# for the gradient descent planner, you must set this to be True
makeSquareCSpace: True

# if not making CSpace square, give it a list of minimum bounds in each cspace
# coordinate direction
minCSpaceBounds:
  - -6.0
  - -6.0

# if not making CSpace square, give it a list of maximum bounds in each cspace
# coordinate direction
maxCSpaceBounds:
  - 36.0
  - 6.0


##
## setup PRM planner params
##

# each of these lists must be the same size

# define a list of max sample numbers to try when running the planner
n: 
  - 500

# define a list of radii in CSpace in which all samples must be connected by a
# line to try when running the planner
r:
  - 2.0

# used to choose whether or not path smoothing should be varied between both
# true and false, or if it should just be on (or just off)
smoothing:
  - True

##
## setup simulation benchmarking
##

# define how many times the PRM should be run with its given settings when doing
# benchmarking and statistical performance analysis
numRunsOfPlannerPerSetting: 50

# define a list of planner paramters to vary parametrically while benchmarking.
# Should correspond to names of planner variables (lists of paramters) in the
# planner config section
paramterNamesToVary:
  - n
  - r
