# coordinates of the robot start state in the workspace
qStart: [0, 0]

# coordinates of the robot goal state in the workspace
qGoal: [35, 0]

# each list element is a list of tuples containing the coordinatesof the
# vertices of the rectangular obstacles in the workspace
WO:
  - [[-6, -6], [25, -6], [25, -5], [-6, -5]]
  - [[-6, 5], [30, 5], [30, 6], [-6, 6]]
  - [[-6, -5], [-5, -5], [-5, 5], [-6, 5]]
  - [[4, -5], [5, -5], [5, 1], [4, 1]]
  - [[9, 0], [10, 0], [10, 5], [9, 5]]
  - [[14, -5], [15, -5], [15, 1], [14, 1]]
  - [[19, 0], [20, 0], [20, 5], [19, 5]]
  - [[24, -5], [25, -5], [25, 1], [24, 1]]
  - [[29, 0], [30, 0], [30, 5], [29, 5]]
