# each list element is a list of tuples containing the coordinates of the
# vertices of the polygonal obstacles in the workspace
WO:
  - [[1, 1], [2, 1], [2, 5], [1, 5]]
  - [[3, 4], [4, 4], [4, 12], [3, 12]]
  - [[3, 12], [12, 12], [12, 13], [3, 13]]
  - [[12, 5], [13, 5], [13, 13], [12, 13]]
  - [[6, 5], [12, 5], [12, 6], [6, 6]]

# coordinates of the robot start state in state space
# [x, y]
startState: [0, 0]

# coordinates of the robot goal state in the workspace
# [x, y]
goalState: [10, 10]

# determines N such that CSpace is discretized into an NxN grid
#
# N = 73 ~ makes a grid cell with a minimum side length ~ 0.25 FOR THIS OBSTACLE
# / START LOCATION SETUP
linearDiscretizationDensity: 73

# determines whether the CSpace will be made square when enlarged for planning.
makeSquareCSpace: False
